apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    - ssh:
        address: 35.239.32.5
        user: chris
        port: 22
        #keyPath: /Users/chris/.ssh/id_rsa
      role: controller
      installFlags:
        - --disable-components konnectivity-server
        - --enable-worker
        - --no-taints
      files:
        - src: ./manifests/admin-console.yaml
          dstDir: /var/lib/k0s/manifests/admin-console
          perm: 0755
    - ssh:
        address: 34.66.197.73 
        user: chris
        port: 22
        #keyPath: /Users/chris/.ssh/id_rsa
      role: controller
      installFlags:
        - --disable-components konnectivity-server
        - --enable-worker
        - --no-taints
      files:
        - src: ./manifests/admin-console.yaml
          dstDir: /var/lib/k0s/manifests/admin-console
          perm: 0755
    - ssh:
        address: 34.134.67.238 
        user: chris
        port: 22
        #keyPath: /Users/chris/.ssh/id_rsa
      role: controller
      installFlags:
        - --disable-components konnectivity-server
        - --enable-worker
        - --no-taints
      files:
        - src: ./manifests/admin-console.yaml
          dstDir: /var/lib/k0s/manifests/admin-console
          perm: 0755
  k0s:
    version: 1.24.2+k0s.0
    dynamicConfig: false
    config:
      spec:
        #network:
        #  provider: calico
        #podSecurityPolicy:
        #  defaultPolicy: 00-k0s-privileged
        extensions:
          helm:
            repositories:
              - name: openebs-localpv
                url: https://openebs.github.io/dynamic-localpv-provisioner
              #- name: replicated
              #  url: oci://registry.replicated.com/library/admin-console
            charts:
              - name: openebs-local-pv
                chartname: openebs-localpv/localpv-provisioner
                namespace: kube-system
                version: "3.2.0"
                values: |
                  openebsNDM:
                    enabled: false
                  deviceClass:
                    enabled: false
                  hostpathClass:
                    name: local
                    isDefaultClass: true
                  fullnameOverride: openebs2
              #- name: kotsadm
              #  chartname: replicated/kotsadm
              #  namespace: kots
              #  version: "1.76.1"
        #  storage:
        #    type: openebs_local_storage
