apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    - ssh:
        address: 34.123.8.31
        user: chris
        port: 22
        #keyPath: /Users/chris/.ssh/id_rsa
      role: controller
      installFlags:
        - --disable-components konnectivity-server
        - --enable-worker
        - --no-taints
      files:
        - src: ./charts/dynamic-localpv-provisioner/deploy/helm/charts/*
          dstDir: /var/lib/charts/dynamic-localpv-provisioner
          perm: 0744
          dirPerm: 0755
    - ssh:
        address: 34.170.144.104
        user: chris
        port: 22
        #keyPath: /Users/chris/.ssh/id_rsa
      role: controller
      installFlags:
        - --disable-components konnectivity-server
        - --enable-worker
        - --no-taints
      files:
        - src: ./charts/dynamic-localpv-provisioner/deploy/helm/charts/*
          dstDir: /var/lib/charts/dynamic-localpv-provisioner
          perm: 0744
    - ssh:
        address: 35.193.241.13 
        user: chris
        port: 22
        #keyPath: /Users/chris/.ssh/id_rsa
      role: controller
      installFlags:
        - --disable-components konnectivity-server
        - --enable-worker
        - --no-taints
      files:
        - src: ./charts/dynamic-localpv-provisioner/deploy/helm/charts/*
          dstDir: /var/lib/charts/dynamic-localpv-provisioner
          perm: 0744
  k0s:
    #version: 1.24.2+k0s.0
    version: 1.23.8+k0s.0
    dynamicConfig: false
    config:
      spec:
        #network:
        #  provider: calico
        #podSecurityPolicy:
        #  defaultPolicy: 00-k0s-privileged
        extensions:
          helm:
            repositories:
              - name: openebs-localpv
                url: https://openebs.github.io/dynamic-localpv-provisioner
              - name: chris-sanders
                url: https://chris-sanders.github.io/helm-charts
            charts:
              - name: openebs-local-pv
                chartname: openebs-localpv/localpv-provisioner
                namespace: kube-system
                version: "3.3.0"
                values: |
                  openebsNDM:
                    enabled: false
                  deviceClass:
                    enabled: false
                  hostpathClass:
                    name: local
                    isDefaultClass: true
                  #localpv:
                  #  replicas: 3
                  fullnameOverride: openebs-local-pv
              - name: kotsadm
                chartname: chris-sanders/admin-console
                namespace: admin-console
                version: "1.76.1"
          #storage:
          #  type: openebs_local_storage
